resolver: nightly-2022-07-10
packages:
- build
- simple-smt
- ghc-tcplugins-trace/ghc-tcplugins-trace
- thoralf/theory
- thoralf/encode
- thoralf/plugin
- thoralf/plugin-rows
- thoralf-uom/plugin
- thoralf-uom/defs
- uom/th
- uom/quantity
- uom/plugin
- uom/defs
- uom/tutorial
- uom/examples
extra-deps:
- ghc-corroborate-1.0.0@sha256:60e580741703235dc81232c41b6a7b29b5cf5e337c92ef1745509e8abf22d2b5,3855