# This YAML file describes your package. Stack will automatically generate a
# Cabal file when you run `stack build`. See the hpack website for help with
# this file: <https://github.com/sol/hpack>.
author: Adam Gundry <adam@well-typed.com>
maintainer: Adam Gundry <adam@well-typed.com>
name: uom-plugin
synopsis: Units of measure as a GHC typechecker plugin
description: |-
    The @uom-plugin@ library adds support for units of measure to GHC
    using the new experimental facility for typechecker plugins, which
    is available in GHC 7.10 and later.  See
    "Data.UnitsOfMeasure.Tutorial" for an introduction to the library.
category: Type System
license: BSD3
license-file: LICENSE
stability: experimental
github: adamgundry/uom-plugin
copyright: Copyright (c) 2014-2018, Adam Gundry
tested-with: >+
  GHC == 8.0.2,
  GHC == 8.2.2,
  GHC == 8.4.4,
  GHC == 8.6.5,
  GHC == 8.8.3
extra-source-files:
- package.yaml
- changelog
ghc-options:
- -Wall
- -fno-warn-unticked-promoted-constructors
library:
  dependencies:
  - base >=4.7 && <5
  - deepseq >=1.3 && <1.5
  - ghc >= 8.0.1 && <8.9
  - ghc-tcplugins-extra >=0.1
  - template-haskell >=2.9
  - containers >=0.5
  - units-parser >=0.1
  source-dirs: src
  exposed-modules:
  - Data.UnitsOfMeasure
  - Data.UnitsOfMeasure.Convert
  - Data.UnitsOfMeasure.Defs
  - Data.UnitsOfMeasure.Internal
  - Data.UnitsOfMeasure.Plugin
  - Data.UnitsOfMeasure.Read
  - Data.UnitsOfMeasure.Show
  - Data.UnitsOfMeasure.Singleton
  - Data.UnitsOfMeasure.Tutorial
tests:
  doctest:
    dependencies:
    - base
    - uom-plugin
    - doctest
    ghc-options:
    - -O0
    other-extensions: TemplateHaskell
    main: DocTest.hs
    source-dirs:
    - test-suite-doctest
    when:
      - condition: impl(ghc > 8.2.2)
        buildable: false
  units:
    dependencies:
    - base
    - uom-plugin
    - tasty >=0.10 && <1.1
    - tasty-hunit >=0.9 && <0.10.1
    ghc-options:
    - -O0
    other-extensions: TemplateHaskell
    main: Tests.hs
    source-dirs:
    - test-suite-units
    when:
      - condition: impl(ghc > 8.2.2)
        buildable: false
  hlint:
    dependencies:
    - base
    - hlint >= 1.7 && <2.3
    ghc-options:
    - -Wall
    - -O0
    - -rtsopts
    - -threaded
    - -with-rtsopts=-N
    main: HLint.hs
    source-dirs:
    - test-suite-hlint
version: '0.3.0.0'
