name: hlint

on:
  pull_request:
  push:

jobs:
  build:
    name: hlint
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
      with:
        submodules: true

    - uses: haskell-actions/hlint-setup@v2
      name: Set up HLint
      with:
        version: "3.6.1"

    - uses: haskell-actions/hlint-run@v2
      name: Run HLint
      with:
        path: '.'
        fail-on: suggestion