name: stan

on:
  push:
  pull_request:

jobs:
  build:
    name: ghc ${{ matrix.ghc }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        cabal: ["3.6"]
        ghc:
          - "8.10.7"

    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true

      - uses: haskell/actions/setup@v1
        name: Setup GHC and cabal-install
        with:
          ghc-version: ${{ matrix.ghc }}
          cabal-version: ${{ matrix.cabal }}

      - uses: actions/cache@v2
        name: cache ~/.cabal/store
        with:
          path: ~/.cabal/store
          key: ${{ runner.os }}-${{ matrix.ghc }}-cabal

      - uses: pavpanchekha/setup-z3@1.2.2
        name: setup z3
        with:
          version: "4.8.7"

      - name: update
        run: cabal update

      - name: install stan
        run: cabal install stan -w ghc-{{matrix.ghc}} --installdir=.bin --install-method=copy --overwrite-policy=always

      - name: build
        run: cabal build all --enable-tests

      - name: run stan
        run: ./bin/stan report

      - run: stan report
      - uses: actions/upload-artifact@v3
        with:
          name: stan-report
          path: ./stan.html
